sudo: required
language: rust
rust:
  - stable
matrix:
  include:
env:
  global:
    - secure: "iTFsbUC9U1KjjIMLeX0Bq7wKn4ICB7q2FFTDgcNX74KW8KPIA8ihCLbOBoA8ds6JjeN5HmMjDqJ3npaeryw6vD1aXY4DQbq1tzuoNsszBnruqwTTy3pbh6Mf1sse8BySXIgfQcFY1pJDXSqSxLtYvypUc8iYCTdx2fSKYReIgHXzLRBvAYb36bRE6tnH4iwPG29NqdUht7UfOsXHPLPLDmK1Zd0y+JdMyPH32lI5hJY+1uWXN4PUvfDXV3aJhSTPrQPfJn7fzntuOAkApO1FLvq8YTIYZ59S1ZE6e6bnl/qIX9HrdBnuaU0hTSOIwXHhJJ9bd0stW63MMj0mffUgOO3oUinXWwgLCA17Nbxbdaq9ZhbVW0QYnqNip5+GGw7bAP85C8AMtqqklCa7Lp/wkG8usS3dsmVT4oy+fMRnxB7za5YZfhfFC6sJG3qPCnRrpAtVuYdJL0Nmo7mVuHUIbt2FM+pIanDFXoZ4PvWYdLg+GQ4RprhRrcYflKaVhdei++uSQOJgdUqkdMa7eW8EQjHH4GqznuiZYewxQTN6E8m9JUgfWHhz8h4/2zCMnz4pooSMkkcPOltwi5Sbjosj7a09Ycla3Yb3PXm9QUJjgmiQcDLbtDYFuq1moHjHll5PKYcvRabgqVqQKDnC+HRTdT+iyzLX5TCaz50w4LJXmlA="
  matrix:
    - FEATURES=""
    - FEATURES="apple-auth"
before_install:
  - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
  - sudo apt-get -y update
  - sudo apt-get -y install libsdl2-dev
script:
  - cargo build --features "$FEATURES"
  - cargo test --features "$FEATURES"
  - (cd client && cargo build --features "$FEATURES")
  - (cd proxy && cargo build --features "$FEATURES")
after_script:
  - |
    if [ "${TRAVIS_BRANCH}" = "master" -a -n "${GH_TOKEN}" ]; then
      cargo doc
      git clone https://github.com/davisp/ghp-import
      ./ghp-import/ghp_import.py -n target/doc
      git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
    fi
